---
# Base Data / GWAS Sum Stats:
# A header is assumed; with the column names P, CHR, POS, BETA, A2, A1 and SNP being expected, where A2 is the effect allele. 
# A rename-file has to be given, however, and header columns can automatically be renamed. 
# Please see the example data, e.g. "example_data/example_phenotype.regenie_chr3.gz_rename"
 base_datasets: 
  example_phenotype: # Start of the values for the example_phenotyp; call it as you like.
   sumstat_file: "example_data/example_phenotype.regenie_chr3.gz" # provide the path to your GWAS sum stats here; a header is required, can be gzipped
   rename_file: "example_data/example_phenotype.regenie_chr3.gz_rename" # needs always to be given, even if no renaming is needed. If no renaming is needed, specify the following dummy file: resources/no_renaming.txt; please see the example data, e.g. "example_data/example_phenotype.regenie_chr3.gz_rename" and use those files as templates.
   col_sep: " " # separator of columns in this base data set; could be also be "\t", ";" or something else
   add_rsid: True # put False if there is already a RSID-column, which should be called/renamed "SNP"
   GRCh: 38 # Reference genome (allowed: 37 or 38), only relevant if rsids should be added
   LOG10P_to_P: True # convert a column that has to be called LOG10P (after renaming) to P-values
   p_cutoff: 1 # prefilter SNPs according to this p-value (all below are retained)
   n_gwas: 600 # number of individuals / n_gwas for PRScs
   
  height: # second base data set; otherwise same as above; copy-paste and then modify this structure for your own, real base data sets.
   sumstat_file: "example_data/GCST90245992_buildGRCh37_chr3.tsv.gz"
   rename_file: "example_data/GCST90245992_buildGRCh37_chr3.tsv.gz_rename"
   col_sep: "\t"
   add_rsid: True
   GRCh: 37
   LOG10P_to_P: False
   p_cutoff: 1
   n_gwas: 1597374


# Target dataset: Binary plink file set which has undergone QC is assumed; rsids can be present in the bim file or it can be added.
 target_dataset:
  bim: "example_data/TGP_EUR_maf05_pruned_chr3.bim"
  bed: "example_data/TGP_EUR_maf05_pruned_chr3.bed"
  fam: "example_data/TGP_EUR_maf05_pruned_chr3.fam"
  add_rsid: True # if rsids are present in the bim file set to "False"
  GRCh: 38 # only relevant when rsIDs should be added (when add_rsid is set to True)


# general settings
 general:
  ld_ref_dir: "example_data/ldblk_ukbb_eur/" # location into which the LD reference panel was unpacked; see PRScs github 
  dbsnp_37_vcf: "ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/00-common_all.vcf.gz" # these are the download links where the dbsnp-ids are retrieved from. Note: there are more comprehensive files available (including non-common alleles) if you have a look at the FTP-server.
  dbsnp_37_tbi: "ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/00-common_all.vcf.gz.tbi"
  dbsnp_38_vcf: "ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/00-common_all.vcf.gz"
  dbsnp_38_tbi: "ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/00-common_all.vcf.gz.tbi"
  chromosomes: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22"] # the chromosomes used
  queue_medium: "medium" # not yet fully implemented: Cluster (i.e. slurm) 
