---
# BASE DATA / GWAS SUM STATS FILES
# A header is assumed; with the column names P, CHR, POS, BETA, A2, A1 and SNP being expected, where A2 is the effect allele. 
# A rename-file can be given, however, and header columns will automatically be renamed. 
# An example file for renaming is given in resources/renaming_file_template.txt, where the first column refers to old column-names, the second to the new ones.
# The column-separator can also be specified. Both "rename_file" and "col_sep" can be left empty, if no renaming is required and if the columns are tab separated.
 base_datasets: 
  example_phenotype:
   sumstat_file: "example_data/example_phenotype.regenie_chr3.gz"
   rename_file: "example_data/example_phenotype.regenie_chr3.gz_rename"
   col_sep: " "
   add_rsid: True
   GRCh: 38
   LOG10P_to_P: True
   p_cutoff: 1
   n_gwas: 600
  height:
   sumstat_file: "example_data/GCST90245992_buildGRCh37_chr3.tsv.gz"
   rename_file: "example_data/GCST90245992_buildGRCh37_chr3.tsv.gz_rename"
   col_sep: "\t"
   add_rsid: True
   GRCh: 37
   LOG10P_to_P: False
   p_cutoff: 1
   n_gwas: 1597374


# Target dataset: Binary plink file set which has undergone QC is assumed; rsids should be present in the bim file or need to be added
 target_dataset:
  bim: "example_data/TGP_EUR_maf05_pruned_chr3.bim"
  bed: "example_data/TGP_EUR_maf05_pruned_chr3.bed"
  fam: "example_data/TGP_EUR_maf05_pruned_chr3.fam"
  add_rsid: True
  GRCh: 38 # only relevant when rsIDs should be added


# general settings
 general:
  ld_ref_dir: "/mnt/int1/PRScs_reference_panels/ldblk_ukbb_eur/" # location into which the LD reference panel was unpacked; see PRScs github 
  dbsnp_37_vcf: https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/00-common_all.vcf.gz
  dbsnp_37_tbi: https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/00-common_all.vcf.gz.tbi
  dbsnp_38_vcf: https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/00-common_all.vcf.gz
  dbsnp_38_tbi: https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/00-common_all.vcf.gz.tbi
  chromosomes: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22"]
  queue_medium: "medium"
